---
run:
    timeout: 3m
    tests: false

linters:
    enable-all: true
    disable:
        # restrictive
        - exhaustruct
        - varnamelen
        - nlreturn
        - funlen
        - nonamedreturns
        - gochecknoglobals
        - wsl
        - nakedret
        - err113
        # deprecated
        - tenv

linters-settings:
    depguard:
        rules:
            main:
                list-mode: strict
                files:
                    - $all
                allow:
                    - $gostd
                    - github.com/stanislav-zeman/go-ddd
                    - github.com/labstack/echo/v4
                    - github.com/jackc/pgx/v5
    dupl:
        threshold: 200
    wrapcheck:
        extra-ignore-sigs:
            - .JSON(

output:
    sort-results: true
    formats:
        - format: colored-line-number
          path: stdout
        - format: tab
          path: golangci-lint.out
