---
name: todos

services:
    todos:
        build:
            dockerfile: Dockerfile.dev
        command: ["mage", "run", "todos"]
        restart: "unless-stopped"
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ".:/app"
        ports:
            - "8080:8080"
        networks: [todos]
        profiles: [api, all]

    postgres:
        image: "postgres:16-alpine"
        restart: "unless-stopped"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: todos
        ports:
            - "5432:5432"
        networks: [todos]
        profiles: [api, dependencies, all]
        volumes:
            - postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d todos'"]
            interval: 1s
            timeout: 2s
            retries: 5

volumes:
    postgres:

networks:
    todos:
        driver: bridge
